import "../../app/globals.scss";
import { Nav } from "@/app/components/nav/nav";
import type { Metadata } from "next";
import styles from "@/app/layout.module.scss";
import MainImg from "../components/mainImg/mainImg";

export const metadata: Metadata = {
  title: "sobokkiworld",
  description: "Generated by soeun",
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Nav />
        <div className={styles.contents}>
          <MainImg />
          {children}
        </div>
      </body>
    </html>
  );
}
