import "../app/globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss"; // CSS 모듈 가져오기

// 다음과 같이 타입을 명확히 지정하거나,
// @ts-ignore를 사용하여 타입 오류를 무시할 수 있습니다.
const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "sobokkiworld",
  description: "Generated by soeun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <div className={styles.container}>{children}</div>
      </body>
    </html>
  );
}
